### PR TITLE
Sort ValidationMessage by its type

### PR DESCRIPTION
**Pull request by jsu216**

### CODE REVIEW

**Review by stevehu — APPROVED** [review]

**Comment by stevehu** [comment]
@jsu216 Thanks a lot for your help.

**Comment by jsu216** [comment]
@stevehu Thank you for approving this. When can we expect a new release including this fix?

**Comment by stevehu** [comment]
I can create a new release immediately. However, it will take some time to update the 1.6.x branch and release it. When do you need it?

**Comment by jsu216** [comment]
Similar to the previous fix, as long as there is a new json-schema-validator release, I can ask the team to use that one with light4j for now.

**Comment by stevehu** [comment]
Done. Please let me know if it works so that I can upgrade the 1.6.x branch to include the latest version. Thanks.

https://github.com/networknt/json-schema-validator/releases/tag/1.0.65

**Comment by jsu216** [comment]
Hi @stevehu , our team just confirm the 1.0.65 version solves their problem. Please go ahead to include it in the latest light4j version. Thanks.

**Pull request merged**
