### PR TITLE
Adding walk capabilities to networknt. 

### PR DESCRIPTION
**Pull request by prashanthjos**
As discussed in the issue #316 , please have a look at the walk capability changes for networknt.

### CODE REVIEW

**Comment by prashanthjos** [comment]
@stevehu please feel free to drop me an email if in doubt. We can discuss more about the changes through a meeting.

**Comment by stevehu** [comment]
Wow! It is a big addition to the library and I like the document and flow picture. It will take some time for me and others to digest. I am sure I will have questions later. Meanwhile, would you be able to merge the latest master branch to your branch so that we can easily compare them? I also send you an invitation for the write access to the repo and you can move your contribution to a branch for easy collaboration if you like. Thanks.

**Comment by prashanthjos** [comment]
@stevehu I updated my fork master branch with latest changes from networknt master branch. We can compare the changes now easily in this PR. Also I created a new branch 'schema_walk_changes' where I have my latest changes. Please let me know if you need any further help in making the merge process easy.

**Review by stevehu — APPROVED** [review]
Although the changes are massive, it is separated from the validator code with careful design. All existing test cases are working, which is an indicator that there would be no impact on the validation functionalities.

**Comment by stevehu** [comment]
@prashanthjos Please test internally and let me know if the feature is fixed. I will release it once we have your confirmation. Thanks.

**Comment by prashanthjos** [comment]
@stevehu Thank you for merging the changes. Yes there is no impact to existing validations and validators. I have tested all the changes locally. This library can now walk or validate the JSON data for a given schema. Any further changes would be minor and can be fixed through small PR's if required. I would request you to create a new release and update the jar version, so that I can start using it.

**Comment by stevehu** [comment]
1.0.44 is released.

**Pull request merged**
