### PR TITLE
Feat/multi-version-tests

### PR DESCRIPTION
**Pull request by jawaff**
This pull request is all about improving the existing unit tests. The current unit tests are mainly using the draft 4 version, but we should be making sure that these unit tests are ran for all of the compatible draft versions. By doing this we can guarantee backwards compatibility between draft versions.

### CODE REVIEW

**Comment by jawaff** [comment]
I'm not ready yet, but I thought I'd open up a draft pull request so you guys know that I didn't forget about this feature.

**Comment by jawaff** [comment]
I'm almost finished with the tests, but my development environment is throwing some strange jacoco error. However, my IDE can run the tests without a problem. This makes it difficult to catch the bugs I'm introducing. I'll get through this.

**Comment by jawaff** [comment]
I may have uncovered a bug that only exists when the later draft versions are used. There's a couple of tests in the MaximumValidatorTest and MinimumValidatorTest classes that only fail when draft versions after v4 are used. I need to investigate some more, but this is a really good find potentially.

**Comment by jawaff** [comment]
I'm going to have to pick this up another time. It's so close to done.

**Comment by eirnym** [comment]
@jawaff Thank you for a PR to improve the tests. 

Could you update your work? 
Is there a chance to split the work and add a few smaller PRs rather than a huge one?

**Comment by stevehu** [comment]
@jawaff @eirnym I am open to any option that can speed up the progress. Thanks.

**Comment by fdutton** [comment]
We are using [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) to ensure compliance with the various specifications and most of the requested functionality is now present. Since this request is so old and has so many conflicts, it seems best to just close it.

**Pull request closed without merging**
