### PR TITLE
Remove incorrect logic for oneOf, anyOf and properties

### PR DESCRIPTION
**Pull request by justin-tay**
This removes the incorrect logic introduced as part of the fixes for
* #110
* #185 

This incorrect logic applies to applicators such as `oneOf` such that it will attempt to special handle cases where there is no validation failures but there are optional properties that are missing.

There is actually no special logic differences between JSON Schema and OpenAPI with regards to the handling of applicators such as `oneOf`. This misunderstanding likely arose due to the incorrect example for `oneOf` on one of the swagger websites which has not been fixed. The OpenAPI spec authors has clarified that the example is wrong and is not compliant with the OpenAPI spec.

* https://github.com/swagger-api/swagger.io/issues/253
* https://github.com/OAI/OpenAPI-Specification/issues/3477

### CODE REVIEW

**Comment by s-ven** [comment]
Hum, should this change have been part of a MINOR revision change ?

Every other release, our validation workflow breaks and we have to refactor our schemas to upgrade to a more recent MINOR revision of networknt

**Comment by stevehu** [comment]
I didn't realize that the changes broke the user's code. What is the best way to have the next release? Should we remove the 1.4.1, 1.4.2 and 1.4.3 and release 1.5.0?

**Comment by justin-tay** [comment]
I think it's too late to remove 1.4.1, 1.4.2, 1.4.3 as now that will break the libraries/users that are already using those versions.

I actually consider this change to be a bug fix. It should be noted that none of the existing tests nor even the additional tests actually hit the affected removed codes. Even the invalid swagger example actually behaved like the standard applicator, ie. the swagger example was already no longer applicable and didn't consider nodes that failed with required to be acceptable, likely this was fixed by other changes as these codes aren't specific to openapi and would have affected the standard json schema evaluations. This possibly introduced very subtle hard to find bugs in standard evaluations.

**Comment by s-ven** [comment]
agree, too late to remove, that's not what I'm asking,
I just wanted you guys to know about this (it happened also when I migrated from 1.3.0 to 1.3.x, I had to refactor the schema builder code)
thanks for prompt answer, and also for building this library !

**Comment by stevehu** [comment]
@s-ven I have merged all the latest PRs and released the 1.5.0 tag. Thanks a lot for the suggestions. It is hard to determine if any change can break users' code as different users will use the library differently. It is important for our users to report these breaking changes to us. Thanks a lot for your help.

**Pull request merged**
