### PR TITLE
#258 fixed cyclic dependencies

### PR DESCRIPTION
**Pull request by francesc79**
@stevehu @mihaiba Thi is my solution for resolved the cyclic dependencies 

- Now the JsonSchema class have a initialize method that load the validators from the schima.
- In the JsonSchemaFactory in the method getSchema from URI I managed a cache. In this case the jsonSchema.initialize is put after the store in the cache for avoid loop. 

Please @mihaiba could you check if your case is covered with my solution?

Regards
Francesco

### CODE REVIEW

**Comment by francesc79** [comment]
@stevehu if you have intention to approve this PR remember to change the url inside CyclicDependencyTest test.

https://raw.githubusercontent.com/francesc79/json-schema-validator/bug/cyclic-dep/src/test/resources/draft4/cyclic/Master.json

**Comment by stevehu** [comment]
@francesc79 I did a merge between two PRs above and the final result works for me. Please review and let me know if you have any concerns. Upon your confirmation, I can release a new version. BTW, could you please add a small document for the urnFactory usage? Thanks.

**Comment by francesc79** [comment]
@stevehu sorry for the late. Today or tomorrow I check and write a documentation about urnFactory

**Comment by francesc79** [comment]
I opened a new PR for documentation. For this PR also work for me. I confirm you merge.

**Comment by stevehu** [comment]
@francesc79 Thanks a lot for your contribution. I have released 1.0.36 to the maven central. 

https://github.com/networknt/json-schema-validator/releases/tag/1.0.36

**Pull request merged**
