### PR TITLE
Improve accuracy of rounding with multipleOf

### PR DESCRIPTION
**Pull request by seamusv**
Ensure the accuracy of the multipleOf contract.

### CODE REVIEW

**Comment by stevehu** [comment]
@seamusv Thanks a lot for your contribution. This makes perfect sense and I am a little surprised that the official test case doesn't cover this scenario. Since we constantly sync the official test cases to our codebase, I think the best option for us is to separate the new test cases to another JSON file. At the same time, let's open an issue to add these to the official test suite. What do you think? 

https://github.com/json-schema-org/JSON-Schema-Test-Suite

**Comment by seamusv** [comment]
@stevehu I can certainly make that request to the other repo.  Where would you suggest this test case be temporarily located since "optional" could also be refreshed?

**Comment by seamusv** [comment]
@stevehu I have moved the test data out of the official specifications and into a top-level JSON file.  The test is only in the draft7 suite.  I'll submit a PR to the official test suite repo.

**Comment by seamusv** [comment]
I have submitted the request at https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/321

**Comment by stevehu** [comment]
@seamusv Thanks a lot for the effort. Whenever we have a separate file, it won't be overwritten.

**Pull request merged**
