### PR TITLE
Changes for adding collector context

### PR DESCRIPTION
**Pull request by prashanthjos**
These changes are with respect to issue #249 . Please let me know your comments.

### CODE REVIEW

**Comment by stevehu** [comment]
@prashanthjos I looked at the code and had hard time understanding how it works. From the test case, it looks like you need to have customized validators to collect the data to the context. Are you expecting the users to provide the customized validators? Is it possible to write a document in the doc folder to let other users know how to leverage this new feature? Thanks.

**Comment by prashanthjos** [comment]
@stevehu I will create a more sophisticated testcase and add a document. But quick explanation of my changes is I have created a singleton class CollectorContext.I have created a Collector interface which users can use to create/specify the objects they want to collect. These Collector objects are added to CollectorContext singleton while the JsonNode’s are being validated inside the validators. I have created a new method  validateAndCollect in JsonSchema class. The purpose of this method is to clear the CollectorContext object before validation and load the CollectorContext with Collector objects after validation. Since CollectorContext object is singleton designed using an enum it can be used anywhere inside the validators without changing any existing signatures. I have demonstrated that in the testcase. Let me know your thoughts.

**Comment by prashanthjos** [comment]
There is no change to the signatures of existing Validators or other classes. Whenever someone needs to collect they get the CollectorContext singleton and add the Collectors to it.

**Comment by stevehu** [comment]
Yes. I see there is no change to the signatures, which is very good. I just want other users to understand the implementation so that they can enjoy the new feature. Thanks a lot for the explanation and clarification.

**Comment by prashanthjos** [comment]
I will come up with a doc and also what is the release cycle networknt follows.Do we merge the code into master branch and increment the version and a set of changes go together?

**Comment by stevehu** [comment]
Yes. We can have another release as soon as it is merged.

**Comment by prashanthjos** [comment]
Sure thank you

**Comment by prashanthjos** [comment]
@stevehu I have changed the CollectorContext to be stored on ThreadLocal. I dint recognize the obvious thread contention issues with Singleton in my earlier commits. I have added some documentation and provided much clear test cases. Please review and let me know your thoughts.

**Comment by stevehu** [comment]
@prashanthjos 1.0.32 is released moment ago. Thanks a lot for your contribution.

**Pull request merged**
