### PR TITLE
Issue #627 custom message for format

### PR DESCRIPTION
**Pull request by vickyrathod**

### CODE REVIEW

**Comment by stevehu** [comment]
It looks good to me. It will be very useful for other users. Would you be able to create a document in the doc folder? Thanks.

**Comment by vickyrathod** [comment]
@stevehu I have updated document for custom messages with example and details, please check.

**Comment by stevehu** [comment]
@vickyrathod Thanks a lot for your help.

**Comment by rajivraghu** [comment]
How to specify custom message for required field??

**Comment by stevehu** [comment]
I think that is standard. something like field name is required.

**Comment by UngeheurenUngeziefer** [comment]
This doesn't work for "required" key, standard message pop up

**Comment by stevehu** [comment]
This keyword doesn't support customized message as it is not necessary.

**Pull request merged**
