### PR TITLE
temporary fix to performance issue

### PR DESCRIPTION
**Pull request by nitin456**

### CODE REVIEW

**Comment by stevehu** [comment]
[fix to performance issue in TypeValidator](https://trello.com/c/RBBNz7E7/13-fix-to-performance-issue-in-typevalidator)

**Comment by nitin456** [comment]
@stevehu please share your comments regarding this change.

**Comment by nitin456** [comment]
@stevehu @chenyan71 @ddobrin @NicholasAzar 
Did you get a chance to review this PR? Please let me know. Thanks.

**Comment by stevehu** [comment]
@nitin456 Thanks a lot for your help. I will test and release it ASAP.

**Comment by nitin456** [comment]
@stevehu, thanks a lot for your encouragement. I hope I can contribute further on this.

**Comment by stevehu** [comment]
Just released a new version with your performance fix. Thanks a lot. 

https://github.com/networknt/json-schema-validator/releases/tag/0.1.24

**Pull request merged**
