### PR TITLE
removed unnecessary check which causes nullable=true, handleNullableFields= true with value=null to fail in all cases except OneOf

### PR DESCRIPTION
**Pull request by harishvashistha**
when nullable = true , handlenullableFields = true and value supplied = null , then getting this failure message `"null found, string expected"` for this example:

```
 "schema": {
      "properties": {
        "values": {
          "type": "string",
          "nullable": true,
          "default": null
        }
      }
    }
```

Data to be created:

```
"data": {
          "values": null
        }
```

Reason appears this unnecessary check for `state.isComplexValidator()` which is true only in case of oneOf . so it suppresses all handleNullableFields configurations causing the above error message.

This is related to my latest query on this issue https://github.com/networknt/json-schema-validator/issues/183

### CODE REVIEW

**Comment by stevehu** [comment]
@harishvashistha Thanks for your PR. I have run the test cases and they all passed from your branch. I cannot remember why we checked the complex validator in the first place but I guess there was a reason for that. I am wondering if we should handle the NULL for all validators or only a limited set of validators.

**Comment by harishvashistha** [comment]
@stevehu @prashanthjos should I merge this PR into another PR that is open https://github.com/networknt/json-schema-validator/pull/555 , which I created for another issue https://github.com/networknt/json-schema-validator/issues/553  ?

We need code changes of both the PRs in your master library at the same time so that we can plan our product release bug free.

**Comment by stevehu** [comment]
No worry. We are looking at both PRs together. Thanks.

**Comment by harishvashistha** [comment]
@SiemelNaran @stevehu @prashanthjos can we get these changes in master release please. This PR is urgently required with PR https://github.com/networknt/json-schema-validator/pull/555 as we are planning a relase on Tuesday.
I hope you would understand the urgency for these changes.

**Comment by harishvashistha** [comment]
@prashanthjos You are requested to please approve and merge this PR and if there are some review comments I can try to add and fix those quickly. This is the highest priority thing I am stuck with in my project.
I hope you would understand.

**Pull request merged**
