### PR TITLE
Setup CI based on GH Actions

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Review by stevehu — APPROVED** [review]

**Comment by stevehu** [comment]
Thanks a lot for your help.

**Comment by stevehu** [comment]
@valfirst It looks like we have some issues with the java 8 build. Java 11 works perfectly. Here is the error message. 

```
Java 8Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3.1.1/dist/codecov' failed with exit code 255
 
```

**Comment by valfirst** [comment]
I've added the same steps as Travis CI had, but I was not able to test Codecov stage due to lack of permissions, I'll try to investigate and fix the error

**Comment by valfirst** [comment]
@stevehu please fin the fixes here: #638

**Comment by valfirst** [comment]
also it's possible to configure codecov comments in PRs: https://docs.codecov.com/docs/pull-request-comments

**Pull request merged**
