### PR TITLE
The bug fix for the issue 520

### PR DESCRIPTION
**Pull request by rabbitloveLHF**
This is the bug fix for issue 520,the issue link is:
https://github.com/networknt/json-schema-validator/issues/520

### CODE REVIEW

**Comment by stevehu** [comment]
@rabbitloveLHF Thanks a lot for your help.

**Comment by stevehu** [comment]
@rabbitloveLHF I found some of the test cases are failing and I have to revert the changes for now. I am wondering if you could take a look at the failed test cases. Thanks.

**Comment by rabbitloveLHF** [comment]
@stevehu Ok,I will look it

**Comment by rabbitloveLHF** [comment]
@stevehu I have know that, it will take some time. Please be patient.

**Comment by stevehu** [comment]
@rabbitloveLHF We are all open source contributors and there is no obligation for anyone. Take your time and thank you very much for your help.

**Pull request merged**
