### PR TITLE
Issue 426 custom message

### PR DESCRIPTION
**Pull request by adilath18**
@stevehu 
#426  Documentation for Custom Error Message
PR: #438

### CODE REVIEW

**Comment by stevehu** [comment]
@adilath18 Thanks a lot for your help.

**Comment by adilath18** [comment]
Thanks a lot for this opportunity. This was my first open-source contribution and enjoyed the experience.

**Comment by stevehu** [comment]
The first contribution is the hardest and I am glad you had an enjoyable experience. Again, thanks a lot for your help and welcome onboard.

**Comment by sambireddyg** [comment]
Hi, I am trying to use the custom message feature. I believe the message implementation should be moved to the attribute level.
In the test case of the pull request the message is at the top level. So, if we have to add a custom message to first name and custom message to foo it is not possible.
the implementation should be 

{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name.",
      "maxLength":10,
 "message": {
    "maxLength" : "Name can be max of 10 characters",
    "type" : "Invalid type"
  }
    },
    "foo": {
      "type": "array",
      "maxItems": 3,
 "message": {
    "maxItems" : "MaxItem must be 3 only",
    "type" : "Invalid type"
  }
    }
  },
 
}

in the getMessageNode we should be using the schemanode directly and get the required message.

**Comment by nitishborade** [comment]
@sambireddyg  @stevehu  @adilath18 
Is it possible adding different message to the same validation type for different properties like @sambireddyg mentioned in his question above.

```json
"prop1": {
      "type": "string",
      "maxLength": 5,
 },
"prop2": {
      "type": "string",
      "maxLength": 10,
 },
```
I need custom messages for both ```prop1``` (```message``` : ```"Max 5 chars"```) and ```prop2``` (```message``` : ```"Max 10 chars"```) , if both fail at the same time.

**Comment by stevehu** [comment]
@everyone I think it is always a good idea to give users more options to customized the error messages. @sambireddyg @nitishborade would you like to try it out and submit a PR? Thanks.

**Comment by Tim-fors** [comment]
> @everyone I think it is always a good idea to give users more options to customized the error messages. @sambireddyg @nitishborade would you like to try it out and submit a PR? Thanks.

@stevehu I would like to look into adding this functionality, should I create a new issue to track this or just open a PR to start a discussion?

**Comment by stevehu** [comment]
Opening a new issue is always better than submitting a PR directly to encourage discussions. Thanks.

**Pull request merged**
