### PR TITLE
#173 - Do not ignore other errors in case of anyOf validator

### PR DESCRIPTION
**Pull request by grssam**
Fixes issue #173 
Also added a way to validate the error count in test cases using the optional int field `"errorCount"`

### CODE REVIEW

**Comment by grssam** [comment]
(closed as the diff is coming out incorrect even after i fixed crlf vs lf)

**Comment by stevehu** [comment]
@grssam It might be easier to create a branch instead of forking the repository to your organization.

**Comment by grssam** [comment]
@stevehu Have sent another after fixing the CRLF issue. My IDE was auto converting to LF while committing.

**Comment by grssam** [comment]
PS: I am not forking in my organization, but in my public user account. That's the ideal/suggested flow for OSS contribution (rather than using the actual repo's side branches) by outsiders :)

**Pull request closed without merging**
