### PR TITLE
Added DateTimeValidator

### PR DESCRIPTION
**Pull request by jiachen1120**
Related issue: https://github.com/networknt/json-schema-validator/issues/138

### CODE REVIEW

**Comment by NicholasAzar** [comment]
@stevehu we should include this in the fix release too, just looking into a change quickly

**Comment by stevehu** [comment]
It is OK. Let's get it reviewed and merged. We can have another release after this.

**Comment by stevehu** [comment]
@jiachen1120 For most application, the date or date-time are generated from datepicker or generated from the client applications. These days, it is very rare that a string format of date can be passed to the API from the UI. I am wondering if you could make this additional date validation optional in the config file. It should be disabled by default and only be enabled if the user knows the API might be hit by invalid date.

**Comment by NicholasAzar** [comment]
@stevehu even if the date is generated from a date picker or whatever client application.. I don't think you would ever want to blindly trust the client and allow invalid dates to be passed
Do you expect the performance overhead to be that significant?

**Comment by stevehu** [comment]
@NicholasAzar The performance hit might not be significant but the date validation is not part of the JSON schema specification. We are enhancing this library to serve our framework; however, we should give users an option to use the library as a standard JSON schema validator. In our framework, we are using the configuration file to control the behavior already and we can set it enabled to true as default from light-codegen. For other users who are using the json-schema-validator as a standalone library, they would expect the standard validation defined in the spec.

**Comment by NicholasAzar** [comment]
@stevehu I'm not sure I follow when you say that date validation is not part of json schema validation.. obviously we have the date & date-time formats, so you're saying that any numbers that fall into that format are automatically valid dates? So a valid date per json schema validation could be 2019-02-31 even though it's not a date in the real world?

**Comment by NicholasAzar** [comment]
Also, from a quick search it does seem like date validation is in fact part of json schema from what I can tell.. json schema says dates should follow RFC3339 here: https://json-schema.org/draft-04/json-schema-validation.html#rfc.section.7.3.1.2

And RFC3339 on page 8 clearly indicates maximum day numbers for specific days here: https://www.ietf.org/rfc/rfc3339.txt

Am i missing something?

**Comment by stevehu** [comment]
@NicholasAzar You are right. I was misled by the other implementations years ago when starting the library. Since there is an RFC for the date-time format, we should follow the RFC.

**Pull request merged**
