### PR TITLE
Allows to override date-time and duration validators

### LINKED ISSUE #784: Custom date-time format not possible since version 1.0.82
In version 1.0.82 the following code was removed from FormatKeyword::newValidator. Making it impossible to add a custom format for date-time. 

```
format = formats.get(formatName);
// if you set custom format, override default Email/DateTime/UUID Validator
if (format != null) {
  return new FormatValidator(schemaPath, schemaNode, parentSchema, validationContext, format, type);
}
```

### PR DESCRIPTION
**Pull request by josejulio**
Fixes #784

### CODE REVIEW

**Review by fdutton — APPROVED** [review]
Looks good to me

**Comment by josejulio** [comment]
thanks @stevehu and @fdutton 

Do you have any idea of when the next release will happen? 
No pressure, just to plan accordingly :smile:

**Comment by stevehu** [comment]
@josejulio I have released 1.0.83, and it will fix the issue. Thanks a lot for your help.

**Comment by josejulio** [comment]
> @josejulio I have released 1.0.83, and it will fix the issue. Thanks a lot for your help.

awesome, thank you!

**Comment by kad-koninr1** [comment]
Thank you @josejulio and @stevehu!

**Pull request merged**
