### PR TITLE
Feature/221

### PR DESCRIPTION
**Pull request by msattel**
This pull request is about Android 6 support (API level >=23) as discussed in https://github.com/networknt/json-schema-validator/issues/221

### CODE REVIEW

**Comment by stevehu** [comment]
@msattel I saw you have set up two different releases to the maven central. I am not familiar with this approach and wondering if you could point me to some documentation or guidelines. In my opinion, we can just downgrade the main release to Java 1.6 and it will work with all environments. What do you think?

**Comment by msattel** [comment]
@stevehu  Sorry, do you mean the changes to the testsources java language level?
Downgrading the code level to 1.6 should work with the changes, so probably having separate settings for the test code is obsolete

**Comment by stevehu** [comment]
@msattel In my opinion, we don't need to do anything with the test folder as they are not part of the release package on the maven central. What we can do is to ensure that src is compiled with JDK 1.6 and test is compiled with JDK 1.8. What do you think?

```
        <java.version>1.6</java.version>
        <java.testversion>1.8</java.testversion>

```

**Comment by msattel** [comment]
@stevehu sound good, from my point of view

**Comment by stevehu** [comment]
@msattel Would you be able to make the adjustment for the PR based on our discussion? Thanks.

**Comment by stevehu** [comment]
@msattel Thanks a lot for your help. Do you know if the binary will be working if I am building with Java 8? I assume it will work but I need somebody to help to confirm.

**Comment by msattel** [comment]
@stevehu thanks a lot for merging it

**Comment by stevehu** [comment]
@msattel Thanks for the confirmation. The codebase is in Java 6 now even the test as some browser cannot separate between main and test. The library is released with JDK8 and I assume it should work.

**Pull request merged**
