### PR TITLE
Fixing concurrency and compilation issues.

### PR DESCRIPTION
**Pull request by prashanthjos**
This PR fixes below issues.

1. Compilation issue in TypeFactoryTest class. Not sure how this compilation issue went in. Commenting the compilation issue on the test class for now. Respective developer can have a look at it.
2. Concurrency issue that can be caused by the static instance variable in BaseJsonValidator class. While setting the attributes of ValidatorState's  by two threads can result in a  "lost update" issue.
3. Updates to Walking. Adding a new WalkFlow Constant.
4. Minor code comment updates.
5. Test case updates.

Please let me know if you see any concerns with the above issues or updated files.

### CODE REVIEW

**Comment by prashanthjos** [comment]
Pre checkin Build or CI/CD is no longer running and this might result in some compilation issues sneaking into master. Can you please take a look at the CI/CD flow also.

**Comment by prashanthjos** [comment]
Hi @stevehu can you please have a look at this PR and can you please merge at your convenience.

**Comment by stevehu** [comment]
@hkupty Could you please take a look at why the lossless test cases are failing after the change? Thanks.

**Comment by prashanthjos** [comment]
@stevehu can you merge this PR if you are OK with the changes. I have commented the test cases causing compilation issues. Also can we have build hooks enabled, so that such issues can be caught early.

**Comment by prashanthjos** [comment]
Also any idea why travis builds are not being triggered?

**Comment by stevehu** [comment]
@prashanthjos I just realized that the Travis build failed. Check the log for the master branch and found the following errors. I am looking into it now. Thanks a lot for raising it.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (test-compile) on project json-schema-validator: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/networknt/json-schema-validator/src/test/java/com/networknt/schema/TypeFactoryTest.java:[57,24] cannot find symbol
[ERROR]   symbol:   variable validValue
[ERROR]   location: class com.networknt.schema.TypeFactoryTest
[ERROR] /home/travis/build/networknt/json-schema-validator/src/test/java/com/networknt/schema/TypeFactoryTest.java:[60,24] cannot find symbol
[ERROR]   symbol:   variable validValue
[ERROR]   location: class com.networknt.schema.TypeFactoryTest
[ERROR] /home/travis/build/networknt/json-schema-validator/src/test/java/com/networknt/schema/TypeFactoryTest.java:[67,20] cannot find symbol
[ERROR]   symbol:   variable validValue
[ERROR]   location: class com.networknt.schema.TypeFactoryTest
[ERROR] /home/travis/build/networknt/json-schema-validator/src/test/java/com/networknt/schema/TypeFactoryTest.java:[70,20] cannot find symbol
[ERROR]   symbol:   variable validValue
[ERROR]   location: class com.networknt.schema.TypeFactoryTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by stevehu** [comment]
@prashanthjos I have fixed the TypeFactoryTest issues and it should be working now in the master branch. Could you please sync from master? It was my mistake when merging the previous PR. Thanks.

**Comment by prashanthjos** [comment]
@stevehu I fixed the merge conflict. Can you please restore Travis CI from next builds.

Can you please merge the PR.

**Comment by hkupty** [comment]
Sorry I missed the notification. What was the issue? Do you still want me to have a look at it?

**Comment by prashanthjos** [comment]
@hkupty I think @stevehu already fixed the issue. @stevehu  can you please release latest version with these changes.

**Comment by stevehu** [comment]
A new release 1.0.50 is out. Thanks. 

https://github.com/networknt/json-schema-validator/releases/tag/1.0.50

**Pull request merged**
