### PR TITLE
Replaced 'new URL' with a call to a new URLFactory 

### PR DESCRIPTION
**Pull request by kenwa**
The original implementation supports schema's to be accessible either in http, http, file, etc.. This pull request adds the possibility to also refer to schema's present in the applications classpath.

### CODE REVIEW

**Comment by stevehu** [comment]
@kenwa Thanks for your help. It is a very nice feature to support loading schema from classpath.

**Comment by kenwa** [comment]
Nice that you liked the feature :-) Just wanted to let you know that a bump of version number accidentally slipped into the PR. You should probably fix that one. 

Any chance that you could create a new release of the library? That would make it possible for us to use that one instead of our forked variant.

**Comment by stevehu** [comment]
@kenwa I have released 0.1.11 minutes ago. I think this is an very unique feature and we need to let other people to enjoy it. Could you please write a unit test case to show people how to use it? The test case can also prevent other PRs to break this feature in the future. Thanks a lot for your contribution.

**Comment by kenwa** [comment]
@stevehu Great! Then we'll use that one instead :-) 

I created a PR with a test case showing how to use the feature a few minutes ago.

**Pull request merged**
