### PR TITLE
Reverts Undertow version to 2.2.25.Final

### LINKED ISSUE #818: Latest does not compile under Java 8
Undertow 2.3.x requires Java 11

### PR DESCRIPTION
**Pull request by fdutton**
Resolves #818

### CODE REVIEW

**Comment by stevehu** [comment]
The undertow is used to start a server for remote references, and it is in test scope. Is there anything wrong with version 2.3.6-Final?

**Comment by fdutton** [comment]
@stevehu Yes, the tests fail in Java 8.

**Comment by fdutton** [comment]
I'm not sure how it was pushed to Maven Central though. None of the builds succeeded.

**Comment by stevehu** [comment]
I realize it now. My local build is using Java 11 by default.

**Pull request merged**
